name:                FunctionalPatterns
version:             0.1.0.0
github:              "kolsrud/function_patterns_demo"
license:             MIT
author:              "Oystein Kolsrud"
maintainer:          "kolsrud@gmail.com"
copyright:           "2018 Oystein Kolsrud"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Demo used for presentation "Functional Patterns for the Object Oriented"
# category:            Demo

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kolsrud/functional_patterns_demo#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck

library:
  source-dirs: src

executables:
  FunctionalPatterns:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FunctionalPatterns
